name: court_dairy
description: "A new Flutter project."

publish_to: "none"

version: 1.0.10+11

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2
  cloud_functions: ^6.0.1
  google_sign_in: ^6.3.0
  firebase_storage: ^13.0.1
  firebase_messaging: ^16.0.1
  animations: ^2.0.11
  get: ^4.7.2
  in_app_update: ^4.2.3
  flutter_local_notifications: ^19.4.1
  get_storage: ^2.1.1
  google_fonts: ^6.3.1
  simple_shadow: ^0.3.1
  flutter_typeahead: ^5.2.0
  lottie: ^3.3.1
  intl: ^0.20.2
  dio: ^5.9.0
  panara_dialogs: ^0.1.5
  image_picker: ^1.2.0
  hugeicons: ^0.0.11
  url_launcher: ^6.3.2
  cached_network_image: ^3.4.1
  animated_text_kit: ^4.2.3
  card_swiper: ^3.0.1
  numberpicker: ^2.1.2
  flutter_bkash: ^0.3.1
  facebook_app_events: ^0.19.3
  uuid: ^4.5.1
  loading_animation_widget: ^1.3.0
  auth_buttons: ^3.0.3
  android_intent_plus: ^5.3.1
  dotted_border: ^2.1.0
  local_auth: ^2.1.7
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0
  flutter_native_splash: ^2.4.6

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splashlogo.png
  color_dark: "#121212"
  image_dark: assets/images/splashlogo.png
  android_12:
    color: "#FFFFFF"
    image: assets/images/splashlogo.png
    icon_background_color: "#FFFFFF"
    color_dark: "#121212"
    image_dark: assets/images/splashlogo.png
    icon_background_color_dark: "#121212"
  android: true
  ios: true
  web: false
