// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXGzTgrSNmGG93biOi8iyap33j-QfaFV0',
    appId: '1:932683268574:web:8e517cdc43b3495b451d4f',
    messagingSenderId: '932683268574',
    projectId: 'court-dairy',
    authDomain: 'court-dairy.firebaseapp.com',
    storageBucket: 'court-dairy.firebasestorage.app',
    measurementId: 'G-ECR8Y7344L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPLFnlR9KTvOOumeAkl3aV0CgU2RTwNlc',
    appId: '1:932683268574:android:5945cf5e0626789e451d4f',
    messagingSenderId: '932683268574',
    projectId: 'court-dairy',
    storageBucket: 'court-dairy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6TmGo56XIVzQRedxp-VQ3eqqbq4W5374',
    appId: '1:932683268574:ios:7dd6fd4038176ffe451d4f',
    messagingSenderId: '932683268574',
    projectId: 'court-dairy',
    storageBucket: 'court-dairy.firebasestorage.app',
    iosBundleId: 'com.appseba.courtdiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6TmGo56XIVzQRedxp-VQ3eqqbq4W5374',
    appId: '1:932683268574:ios:e627a75dd9ac38b9451d4f',
    messagingSenderId: '932683268574',
    projectId: 'court-dairy',
    storageBucket: 'court-dairy.firebasestorage.app',
    iosBundleId: 'com.example.courtdiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXGzTgrSNmGG93biOi8iyap33j-QfaFV0',
    appId: '1:932683268574:web:e3c5565d9d6bd3a5451d4f',
    messagingSenderId: '932683268574',
    projectId: 'court-dairy',
    authDomain: 'court-dairy.firebaseapp.com',
    storageBucket: 'court-dairy.firebasestorage.app',
    measurementId: 'G-J6V7GXT256',
  );

}