// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz1dvWUgIYUlvlYd9opPkfvct9t9Jfuf0',
    appId: '1:119871249139:web:72bb3e72b66c6e6ee4b586',
    messagingSenderId: '119871249139',
    projectId: 'court-diary-72689',
    authDomain: 'court-diary-72689.firebaseapp.com',
    storageBucket: 'court-diary-72689.firebasestorage.app',
    measurementId: 'G-DEXDWFNKQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvvdyh-CIZRZIycTt0h96pt_yVx1ES9t8',
    appId: '1:119871249139:android:60cb34844b6949d7e4b586',
    messagingSenderId: '119871249139',
    projectId: 'court-diary-72689',
    storageBucket: 'court-diary-72689.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSiR4GHRjlwNPrVFA1sE-PV3Xmj37ZApg',
    appId: '1:119871249139:ios:90a3e440464b711ee4b586',
    messagingSenderId: '119871249139',
    projectId: 'court-diary-72689',
    storageBucket: 'court-diary-72689.firebasestorage.app',
    iosClientId: '119871249139-u5u60616aia4kubngug4md2j1ilhilpa.apps.googleusercontent.com',
    iosBundleId: 'com.appseba.courtdiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSiR4GHRjlwNPrVFA1sE-PV3Xmj37ZApg',
    appId: '1:119871249139:ios:f81b851cba7fb5a8e4b586',
    messagingSenderId: '119871249139',
    projectId: 'court-diary-72689',
    storageBucket: 'court-diary-72689.firebasestorage.app',
    iosClientId: '119871249139-dqugf4mscsine3lmg9snpgq40uttokqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.courtDairy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz1dvWUgIYUlvlYd9opPkfvct9t9Jfuf0',
    appId: '1:119871249139:web:d488a64b8585ba8be4b586',
    messagingSenderId: '119871249139',
    projectId: 'court-diary-72689',
    authDomain: 'court-diary-72689.firebaseapp.com',
    storageBucket: 'court-diary-72689.firebasestorage.app',
    measurementId: 'G-RN2WW8L9XH',
  );

}